import type { SetType } from "@/api/sets/types";

export function autoGeneratedSetName(
  setType: SetType | null,
  artistNames: string[],
): string {
  if (setType !== "music") return "";
  if (artistNames.length === 0) return "";
  if (artistNames.length === 1) return artistNames[0];
  if (artistNames.length === 2) {
    return `${artistNames[0]} vs ${artistNames[1]}`;
  }
  return `${artistNames[0]} + ${artistNames.length - 1} more`;
}
