project_id = "qssmazlqrmxiudxckxvi"

[functions.sync-artist-data]
verify_jwt = false

[auth.email.template.magic_link]
subject = "Welcome to the Festival!"
content_path = "./supabase/templates/magic_link.html"