import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import type { Database } from "@/integrations/supabase/types";
import { FestivalSet, setsKeys } from "./types";

type SetInsert = Database["public"]["Tables"]["sets"]["Insert"];

// Mutation function
async function createSet(
  setData: Omit<
    FestivalSet,
    | "id"
    | "created_at"
    | "updated_at"
    | "artists"
    | "votes"
    | "stages"
    | "archived"
    | "slug"
  >,
): Promise<FestivalSet> {
  const insertData: SetInsert = {
    name: setData.name,
    description: setData.description,
    festival_edition_id: setData.festival_edition_id,
    stage_id: setData.stage_id,
    time_start: setData.time_start,
    time_end: setData.time_end,
    created_by: setData.created_by,
    set_type: setData.set_type,
    external_url: setData.external_url,
    slug: "", // auto-generated by the sets_dedupe_slug DB trigger
    archived: false,
  };

  const { data, error } = await supabase
    .from("sets")
    .insert(insertData)
    .select()
    .single();

  if (error) {
    console.error("Error creating set:", error);
    throw new Error("Failed to create set");
  }

  return {
    ...data,
    artists: [],
    votes: [],
  };
}

// Hook
export function useCreateSetMutation() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: createSet,
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: setsKeys.all,
      });
      toast({
        title: "Success",
        description: "Set created successfully",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error?.message || "Failed to create set",
        variant: "destructive",
      });
    },
  });
}
