import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { uploadArtistLogo } from "@/services/storage";
import type { Artist } from "./types";
import { artistsKeys } from "./types";

type CreateArtistInput = Omit<
  Artist,
  | "created_at"
  | "updated_at"
  | "archived"
  | "artist_music_genres"
  | "id"
  | "last_soundcloud_sync"
  | "soundcloud_followers"
  | "votes"
  | "estimated_date"
  | "slug"
  | "stage"
  | "time_end"
  | "time_start"
> & {
  genre_ids: string[];
  /** Takes priority over `image_url` when present; a failed upload falls back to `image_url`. */
  logoFile?: File | null;
};

// Mutation function
async function createArtist(
  artistData: CreateArtistInput,
): Promise<{ artist: Artist; imageUploadFailed: boolean }> {
  const { genre_ids, logoFile, image_url, ...artist } = artistData;

  let resolvedImageUrl = image_url;
  let imageUploadFailed = false;
  if (logoFile) {
    try {
      const uploadResult = await uploadArtistLogo(
        logoFile,
        crypto.randomUUID(),
      );
      resolvedImageUrl = uploadResult.url;
    } catch (uploadError) {
      console.error("Image upload failed:", uploadError);
      imageUploadFailed = true;
    }
  }

  const { data, error } = await supabase
    .from("artists")
    .insert({
      ...artist,
      image_url: resolvedImageUrl,
      slug: "", // auto-generated by the artists_dedupe_slug DB trigger
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    })
    .select("*")
    .single();

  if (error) {
    console.error("Error creating artist:", error);
    throw new Error("Failed to create artist");
  }

  if (genre_ids.length > 0) {
    const { error: genreError } = await supabase
      .from("artist_music_genres")
      .insert(
        genre_ids.map((genreId) => ({
          artist_id: data.id,
          music_genre_id: genreId,
        })),
      );

    if (genreError) {
      console.error("Error adding genres:", genreError);
      throw new Error("Failed to add genres");
    }
  }

  return {
    artist: {
      ...data,
      artist_music_genres: genre_ids.map((genreId) => ({
        music_genre_id: genreId,
      })),
    },
    imageUploadFailed,
  };
}

// Hook
export function useCreateArtistMutation() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: createArtist,
    onSuccess: ({ imageUploadFailed }) => {
      queryClient.invalidateQueries({
        queryKey: artistsKeys.all,
      });
      // One toast, not two — the toast store only keeps the latest, so a
      // separate "upload failed" + "created successfully" pair would just
      // have the second silently clobber the first.
      toast(
        imageUploadFailed
          ? {
              title: "Artist created",
              description: "Image upload failed, using URL instead",
              variant: "destructive",
            }
          : {
              title: "Success",
              description: "Artist created successfully",
            },
      );
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error?.message || "Failed to create artist",
        variant: "destructive",
      });
    },
  });
}
