import type { Database } from "@/integrations/supabase/types";
import { registerCleanup, testSupabase } from "../harness";
import { SEEDED_USER_ID } from "./constants";

type ArtistInsert = Database["public"]["Tables"]["artists"]["Insert"];

/** Creates a uniquely-named artist and self-registers its cleanup. */
export async function createArtist(
  overrides: Partial<ArtistInsert> = {},
): Promise<string> {
  const suffix = crypto.randomUUID();

  const { data, error } = await testSupabase
    .from("artists")
    .insert({
      name: `Scratch Artist ${suffix}`,
      slug: "", // auto-generated by the artists_dedupe_slug DB trigger
      added_by: SEEDED_USER_ID,
      ...overrides,
    })
    .select("id")
    .single();
  if (error) throw error;

  registerCleanup(async () => {
    const { error: deleteError } = await testSupabase
      .from("artists")
      .delete()
      .eq("id", data.id);
    if (deleteError) throw deleteError;
  });

  return data.id;
}
