import type { Database } from "@/integrations/supabase/types";
import { registerCleanup, testSupabase } from "../harness";
import { SEEDED_USER_ID } from "./constants";
import { createScratchFestivalEdition } from "./scratchPool";

type SetInsert = Database["public"]["Tables"]["sets"]["Insert"];

// Creates a uniquely-named set and self-registers its cleanup with the
// harness, so tests never hand-write their own insert/delete for one. Pass
// `festival_edition_id` to scope it to a specific edition; otherwise a fresh
// scratch edition is created for it.
export async function createSet(
  overrides: Partial<SetInsert> = {},
): Promise<string> {
  const suffix = crypto.randomUUID();
  const festival_edition_id =
    overrides.festival_edition_id ?? (await createScratchFestivalEdition());

  const { data, error } = await testSupabase
    .from("sets")
    .insert({
      name: `Scratch Set ${suffix}`,
      slug: "", // auto-generated by the sets_dedupe_slug DB trigger
      created_by: SEEDED_USER_ID,
      ...overrides,
      festival_edition_id,
    })
    .select("id")
    .single();
  if (error) throw error;

  registerCleanup(async () => {
    const { error: deleteError } = await testSupabase
      .from("sets")
      .delete()
      .eq("id", data.id);
    if (deleteError) throw deleteError;
  });

  return data.id;
}
