// Generated from /usr/share/zoneinfo/zone1970.tab (IANA tz database).
// Maps IANA timezone -> ISO 3166 alpha-2 country codes; the first code is
// the primary country. Shared zones (e.g. Europe/Berlin) list all overlapping
// countries so country search hits them too.
//
// Regenerate with: node scripts/gen-zone-countries.mjs

export const ZONE_COUNTRIES: Record<string, readonly string[]> = {
  "Africa/Abidjan": [
    "CI",
    "BF",
    "GH",
    "GM",
    "GN",
    "IS",
    "ML",
    "MR",
    "SH",
    "SL",
    "SN",
    "TG",
  ],
  "Africa/Algiers": ["DZ"],
  "Africa/Bissau": ["GW"],
  "Africa/Cairo": ["EG"],
  "Africa/Casablanca": ["MA"],
  "Africa/Ceuta": ["ES"],
  "Africa/El_Aaiun": ["EH"],
  "Africa/Johannesburg": ["ZA", "LS", "SZ"],
  "Africa/Juba": ["SS"],
  "Africa/Khartoum": ["SD"],
  "Africa/Lagos": ["NG", "AO", "BJ", "CD", "CF", "CG", "CM", "GA", "GQ", "NE"],
  "Africa/Maputo": ["MZ", "BI", "BW", "CD", "MW", "RW", "ZM", "ZW"],
  "Africa/Monrovia": ["LR"],
  "Africa/Nairobi": [
    "KE",
    "DJ",
    "ER",
    "ET",
    "KM",
    "MG",
    "SO",
    "TZ",
    "UG",
    "YT",
  ],
  "Africa/Ndjamena": ["TD"],
  "Africa/Sao_Tome": ["ST"],
  "Africa/Tripoli": ["LY"],
  "Africa/Tunis": ["TN"],
  "Africa/Windhoek": ["NA"],
  "America/Adak": ["US"],
  "America/Anchorage": ["US"],
  "America/Araguaina": ["BR"],
  "America/Argentina/Buenos_Aires": ["AR"],
  "America/Argentina/Catamarca": ["AR"],
  "America/Argentina/Cordoba": ["AR"],
  "America/Argentina/Jujuy": ["AR"],
  "America/Argentina/La_Rioja": ["AR"],
  "America/Argentina/Mendoza": ["AR"],
  "America/Argentina/Rio_Gallegos": ["AR"],
  "America/Argentina/Salta": ["AR"],
  "America/Argentina/San_Juan": ["AR"],
  "America/Argentina/San_Luis": ["AR"],
  "America/Argentina/Tucuman": ["AR"],
  "America/Argentina/Ushuaia": ["AR"],
  "America/Asuncion": ["PY"],
  "America/Bahia": ["BR"],
  "America/Bahia_Banderas": ["MX"],
  "America/Barbados": ["BB"],
  "America/Belem": ["BR"],
  "America/Belize": ["BZ"],
  "America/Boa_Vista": ["BR"],
  "America/Bogota": ["CO"],
  "America/Boise": ["US"],
  "America/Cambridge_Bay": ["CA"],
  "America/Campo_Grande": ["BR"],
  "America/Cancun": ["MX"],
  "America/Caracas": ["VE"],
  "America/Cayenne": ["GF"],
  "America/Chicago": ["US"],
  "America/Chihuahua": ["MX"],
  "America/Ciudad_Juarez": ["MX"],
  "America/Costa_Rica": ["CR"],
  "America/Coyhaique": ["CL"],
  "America/Cuiaba": ["BR"],
  "America/Danmarkshavn": ["GL"],
  "America/Dawson": ["CA"],
  "America/Dawson_Creek": ["CA"],
  "America/Denver": ["US"],
  "America/Detroit": ["US"],
  "America/Edmonton": ["CA"],
  "America/Eirunepe": ["BR"],
  "America/El_Salvador": ["SV"],
  "America/Fort_Nelson": ["CA"],
  "America/Fortaleza": ["BR"],
  "America/Glace_Bay": ["CA"],
  "America/Goose_Bay": ["CA"],
  "America/Grand_Turk": ["TC"],
  "America/Guatemala": ["GT"],
  "America/Guayaquil": ["EC"],
  "America/Guyana": ["GY"],
  "America/Halifax": ["CA"],
  "America/Havana": ["CU"],
  "America/Hermosillo": ["MX"],
  "America/Indiana/Indianapolis": ["US"],
  "America/Indiana/Knox": ["US"],
  "America/Indiana/Marengo": ["US"],
  "America/Indiana/Petersburg": ["US"],
  "America/Indiana/Tell_City": ["US"],
  "America/Indiana/Vevay": ["US"],
  "America/Indiana/Vincennes": ["US"],
  "America/Indiana/Winamac": ["US"],
  "America/Inuvik": ["CA"],
  "America/Iqaluit": ["CA"],
  "America/Jamaica": ["JM"],
  "America/Juneau": ["US"],
  "America/Kentucky/Louisville": ["US"],
  "America/Kentucky/Monticello": ["US"],
  "America/La_Paz": ["BO"],
  "America/Lima": ["PE"],
  "America/Los_Angeles": ["US"],
  "America/Maceio": ["BR"],
  "America/Managua": ["NI"],
  "America/Manaus": ["BR"],
  "America/Martinique": ["MQ"],
  "America/Matamoros": ["MX"],
  "America/Mazatlan": ["MX"],
  "America/Menominee": ["US"],
  "America/Merida": ["MX"],
  "America/Metlakatla": ["US"],
  "America/Mexico_City": ["MX"],
  "America/Miquelon": ["PM"],
  "America/Moncton": ["CA"],
  "America/Monterrey": ["MX"],
  "America/Montevideo": ["UY"],
  "America/New_York": ["US"],
  "America/Nome": ["US"],
  "America/Noronha": ["BR"],
  "America/North_Dakota/Beulah": ["US"],
  "America/North_Dakota/Center": ["US"],
  "America/North_Dakota/New_Salem": ["US"],
  "America/Nuuk": ["GL"],
  "America/Ojinaga": ["MX"],
  "America/Panama": ["PA", "CA", "KY"],
  "America/Paramaribo": ["SR"],
  "America/Phoenix": ["US", "CA"],
  "America/Port-au-Prince": ["HT"],
  "America/Porto_Velho": ["BR"],
  "America/Puerto_Rico": [
    "PR",
    "AG",
    "CA",
    "AI",
    "AW",
    "BL",
    "BQ",
    "CW",
    "DM",
    "GD",
    "GP",
    "KN",
    "LC",
    "MF",
    "MS",
    "SX",
    "TT",
    "VC",
    "VG",
    "VI",
  ],
  "America/Punta_Arenas": ["CL"],
  "America/Rankin_Inlet": ["CA"],
  "America/Recife": ["BR"],
  "America/Regina": ["CA"],
  "America/Resolute": ["CA"],
  "America/Rio_Branco": ["BR"],
  "America/Santarem": ["BR"],
  "America/Santiago": ["CL"],
  "America/Santo_Domingo": ["DO"],
  "America/Sao_Paulo": ["BR"],
  "America/Scoresbysund": ["GL"],
  "America/Sitka": ["US"],
  "America/St_Johns": ["CA"],
  "America/Swift_Current": ["CA"],
  "America/Tegucigalpa": ["HN"],
  "America/Thule": ["GL"],
  "America/Tijuana": ["MX"],
  "America/Toronto": ["CA", "BS"],
  "America/Vancouver": ["CA"],
  "America/Whitehorse": ["CA"],
  "America/Winnipeg": ["CA"],
  "America/Yakutat": ["US"],
  "Antarctica/Casey": ["AQ"],
  "Antarctica/Davis": ["AQ"],
  "Antarctica/Macquarie": ["AU"],
  "Antarctica/Mawson": ["AQ"],
  "Antarctica/Palmer": ["AQ"],
  "Antarctica/Rothera": ["AQ"],
  "Antarctica/Troll": ["AQ"],
  "Antarctica/Vostok": ["AQ"],
  "Asia/Almaty": ["KZ"],
  "Asia/Amman": ["JO"],
  "Asia/Anadyr": ["RU"],
  "Asia/Aqtau": ["KZ"],
  "Asia/Aqtobe": ["KZ"],
  "Asia/Ashgabat": ["TM"],
  "Asia/Atyrau": ["KZ"],
  "Asia/Baghdad": ["IQ"],
  "Asia/Baku": ["AZ"],
  "Asia/Bangkok": ["TH", "CX", "KH", "LA", "VN"],
  "Asia/Barnaul": ["RU"],
  "Asia/Beirut": ["LB"],
  "Asia/Bishkek": ["KG"],
  "Asia/Chita": ["RU"],
  "Asia/Colombo": ["LK"],
  "Asia/Damascus": ["SY"],
  "Asia/Dhaka": ["BD"],
  "Asia/Dili": ["TL"],
  "Asia/Dubai": ["AE", "OM", "RE", "SC", "TF"],
  "Asia/Dushanbe": ["TJ"],
  "Asia/Famagusta": ["CY"],
  "Asia/Gaza": ["PS"],
  "Asia/Hebron": ["PS"],
  "Asia/Ho_Chi_Minh": ["VN"],
  "Asia/Hong_Kong": ["HK"],
  "Asia/Hovd": ["MN"],
  "Asia/Irkutsk": ["RU"],
  "Asia/Jakarta": ["ID"],
  "Asia/Jayapura": ["ID"],
  "Asia/Jerusalem": ["IL"],
  "Asia/Kabul": ["AF"],
  "Asia/Kamchatka": ["RU"],
  "Asia/Karachi": ["PK"],
  "Asia/Kathmandu": ["NP"],
  "Asia/Khandyga": ["RU"],
  "Asia/Kolkata": ["IN"],
  "Asia/Krasnoyarsk": ["RU"],
  "Asia/Kuching": ["MY", "BN"],
  "Asia/Macau": ["MO"],
  "Asia/Magadan": ["RU"],
  "Asia/Makassar": ["ID"],
  "Asia/Manila": ["PH"],
  "Asia/Nicosia": ["CY"],
  "Asia/Novokuznetsk": ["RU"],
  "Asia/Novosibirsk": ["RU"],
  "Asia/Omsk": ["RU"],
  "Asia/Oral": ["KZ"],
  "Asia/Pontianak": ["ID"],
  "Asia/Pyongyang": ["KP"],
  "Asia/Qatar": ["QA", "BH"],
  "Asia/Qostanay": ["KZ"],
  "Asia/Qyzylorda": ["KZ"],
  "Asia/Riyadh": ["SA", "AQ", "KW", "YE"],
  "Asia/Sakhalin": ["RU"],
  "Asia/Samarkand": ["UZ"],
  "Asia/Seoul": ["KR"],
  "Asia/Shanghai": ["CN"],
  "Asia/Singapore": ["SG", "AQ", "MY"],
  "Asia/Srednekolymsk": ["RU"],
  "Asia/Taipei": ["TW"],
  "Asia/Tashkent": ["UZ"],
  "Asia/Tbilisi": ["GE"],
  "Asia/Tehran": ["IR"],
  "Asia/Thimphu": ["BT"],
  "Asia/Tokyo": ["JP", "AU"],
  "Asia/Tomsk": ["RU"],
  "Asia/Ulaanbaatar": ["MN"],
  "Asia/Urumqi": ["CN"],
  "Asia/Ust-Nera": ["RU"],
  "Asia/Vladivostok": ["RU"],
  "Asia/Yakutsk": ["RU"],
  "Asia/Yangon": ["MM", "CC"],
  "Asia/Yekaterinburg": ["RU"],
  "Asia/Yerevan": ["AM"],
  "Atlantic/Azores": ["PT"],
  "Atlantic/Bermuda": ["BM"],
  "Atlantic/Canary": ["ES"],
  "Atlantic/Cape_Verde": ["CV"],
  "Atlantic/Faroe": ["FO"],
  "Atlantic/Madeira": ["PT"],
  "Atlantic/South_Georgia": ["GS"],
  "Atlantic/Stanley": ["FK"],
  "Australia/Adelaide": ["AU"],
  "Australia/Brisbane": ["AU"],
  "Australia/Broken_Hill": ["AU"],
  "Australia/Darwin": ["AU"],
  "Australia/Eucla": ["AU"],
  "Australia/Hobart": ["AU"],
  "Australia/Lindeman": ["AU"],
  "Australia/Lord_Howe": ["AU"],
  "Australia/Melbourne": ["AU"],
  "Australia/Perth": ["AU"],
  "Australia/Sydney": ["AU"],
  "Europe/Andorra": ["AD"],
  "Europe/Astrakhan": ["RU"],
  "Europe/Athens": ["GR"],
  "Europe/Belgrade": ["RS", "BA", "HR", "ME", "MK", "SI"],
  "Europe/Berlin": ["DE", "DK", "NO", "SE", "SJ"],
  "Europe/Brussels": ["BE", "LU", "NL"],
  "Europe/Bucharest": ["RO"],
  "Europe/Budapest": ["HU"],
  "Europe/Chisinau": ["MD"],
  "Europe/Dublin": ["IE"],
  "Europe/Gibraltar": ["GI"],
  "Europe/Helsinki": ["FI", "AX"],
  "Europe/Istanbul": ["TR"],
  "Europe/Kaliningrad": ["RU"],
  "Europe/Kirov": ["RU"],
  "Europe/Kyiv": ["UA"],
  "Europe/Lisbon": ["PT"],
  "Europe/London": ["GB", "GG", "IM", "JE"],
  "Europe/Madrid": ["ES"],
  "Europe/Malta": ["MT"],
  "Europe/Minsk": ["BY"],
  "Europe/Moscow": ["RU"],
  "Europe/Paris": ["FR", "MC"],
  "Europe/Prague": ["CZ", "SK"],
  "Europe/Riga": ["LV"],
  "Europe/Rome": ["IT", "SM", "VA"],
  "Europe/Samara": ["RU"],
  "Europe/Saratov": ["RU"],
  "Europe/Simferopol": ["RU", "UA"],
  "Europe/Sofia": ["BG"],
  "Europe/Tallinn": ["EE"],
  "Europe/Tirane": ["AL"],
  "Europe/Ulyanovsk": ["RU"],
  "Europe/Vienna": ["AT"],
  "Europe/Vilnius": ["LT"],
  "Europe/Volgograd": ["RU"],
  "Europe/Warsaw": ["PL"],
  "Europe/Zurich": ["CH", "DE", "LI"],
  "Indian/Chagos": ["IO"],
  "Indian/Maldives": ["MV", "TF"],
  "Indian/Mauritius": ["MU"],
  "Pacific/Apia": ["WS"],
  "Pacific/Auckland": ["NZ", "AQ"],
  "Pacific/Bougainville": ["PG"],
  "Pacific/Chatham": ["NZ"],
  "Pacific/Easter": ["CL"],
  "Pacific/Efate": ["VU"],
  "Pacific/Fakaofo": ["TK"],
  "Pacific/Fiji": ["FJ"],
  "Pacific/Galapagos": ["EC"],
  "Pacific/Gambier": ["PF"],
  "Pacific/Guadalcanal": ["SB", "FM"],
  "Pacific/Guam": ["GU", "MP"],
  "Pacific/Honolulu": ["US"],
  "Pacific/Kanton": ["KI"],
  "Pacific/Kiritimati": ["KI"],
  "Pacific/Kosrae": ["FM"],
  "Pacific/Kwajalein": ["MH"],
  "Pacific/Marquesas": ["PF"],
  "Pacific/Nauru": ["NR"],
  "Pacific/Niue": ["NU"],
  "Pacific/Norfolk": ["NF"],
  "Pacific/Noumea": ["NC"],
  "Pacific/Pago_Pago": ["AS", "UM"],
  "Pacific/Palau": ["PW"],
  "Pacific/Pitcairn": ["PN"],
  "Pacific/Port_Moresby": ["PG", "AQ", "FM"],
  "Pacific/Rarotonga": ["CK"],
  "Pacific/Tahiti": ["PF"],
  "Pacific/Tarawa": ["KI", "MH", "TV", "UM", "WF"],
  "Pacific/Tongatapu": ["TO"],
};
