import type { SetType } from "@/api/sets/types";
import { autoGeneratedSetName } from "@/lib/setNameGeneration";

export interface NamedArtist {
  id: string;
  name: string;
}

export function generateSetName(
  setType: SetType | null,
  artists: NamedArtist[],
  artistIds: string[],
): string {
  const artistNames = artists
    .filter((artist) => artistIds.includes(artist.id))
    .map((artist) => artist.name);
  return autoGeneratedSetName(setType, artistNames);
}
