import { describe, expect, it } from "vitest";
import { autoGeneratedSetName } from "./generateSetName";

describe("autoGeneratedSetName", () => {
  it("joins artist names for music sets", () => {
    expect(autoGeneratedSetName("music", [])).toBe("");
    expect(autoGeneratedSetName("music", ["Shpongle"])).toBe("Shpongle");
    expect(autoGeneratedSetName("music", ["Shpongle", "Ott"])).toBe(
      "Shpongle vs Ott",
    );
    expect(autoGeneratedSetName("music", ["Shpongle", "Ott", "Bonobo"])).toBe(
      "Shpongle + 2 more",
    );
  });

  it("never generates a name for non-music sets", () => {
    expect(autoGeneratedSetName("workshop", ["Shpongle"])).toBe("");
    expect(autoGeneratedSetName("performance", ["Shpongle", "Ott"])).toBe("");
    expect(autoGeneratedSetName("other", ["Shpongle"])).toBe("");
  });

  it("never generates a name when no type is chosen", () => {
    expect(autoGeneratedSetName(null, ["Shpongle"])).toBe("");
  });
});
