import type { SetType } from "@/api/sets/types";

export interface NamedArtist {
  id: string;
  name: string;
}

export function generateSetName(
  setType: SetType | null,
  artists: NamedArtist[],
  artistIds: string[],
): string {
  const artistNames = artists
    .filter((artist) => artistIds.includes(artist.id))
    .map((artist) => artist.name);
  return autoGeneratedSetName(setType, artistNames);
}

export function autoGeneratedSetName(
  setType: SetType | null,
  artistNames: string[],
): string {
  if (setType !== "music") return "";
  if (artistNames.length === 0) return "";
  if (artistNames.length === 1) return artistNames[0];
  if (artistNames.length === 2) {
    return `${artistNames[0]} vs ${artistNames[1]}`;
  }
  return `${artistNames[0]} + ${artistNames.length - 1} more`;
}
