-- Neutralized: this migration originally seeded a hardcoded artist roster and
-- depended on a `profiles` row (for `artists.added_by`) created by the
-- now-neutralized 20250620080928_seed_artists_data.sql. Seed data does not
-- belong in migrations -- supabase/seed.sql is the supported mechanism and
-- staging/prod-like data comes from scripts/sync-from-prod.sh.
--
-- The body is kept as a no-op so the migration history stays intact on
-- environments where it already ran.
