-- Neutralized: this migration originally seeded a hardcoded artist roster and
-- a `system@boom-voter.local` auth user. Seed data does not belong in
-- migrations -- supabase/seed.sql is the supported mechanism and the CLI
-- applies it automatically on `db reset` / `start`. Staging/prod-like data
-- comes from scripts/sync-from-prod.sh.
--
-- The body is kept as a no-op so the migration history stays intact on
-- environments where it already ran.
