// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { createSupabaseStorage } from "@/lib/crossDomainStorage";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. " +
      "For local dev: copy .env.local.example to .env.local and run `supabase start`. " +
      "For deploys: set them in your hosting provider's environment variables.",
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: createSupabaseStorage(),
      storageKey: "sb-auth-token",
      // Use cross-domain cookies for production
      flowType: "pkce",
    },
  },
);
